/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pboproject;

/**
 *
 * @author ASUS
 */
public class Convert extends javax.swing.JFrame {

    /**
     * Creates new form Convert
     */
    public Convert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Jaraktxt = new javax.swing.JTextField();
        Jarakbox1 = new javax.swing.JComboBox<>();
        Waktutxt = new javax.swing.JTextField();
        Waktubox1 = new javax.swing.JComboBox<>();
        Suhutxt = new javax.swing.JTextField();
        Suhubox1 = new javax.swing.JComboBox<>();
        Jarakhasil = new javax.swing.JTextField();
        Waktuhasil = new javax.swing.JTextField();
        Suhuhasil = new javax.swing.JTextField();
        Jarakbox2 = new javax.swing.JComboBox<>();
        Waktubox2 = new javax.swing.JComboBox<>();
        Suhubox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(219, 226, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Jaraktxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JaraktxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JaraktxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JaraktxtKeyTyped(evt);
            }
        });

        Jarakbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km", "hm", "dam", "m", "dm", "cm", "mm" }));
        Jarakbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Jarakbox1ItemStateChanged(evt);
            }
        });
        Jarakbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jarakbox1ActionPerformed(evt);
            }
        });

        Waktutxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WaktutxtKeyReleased(evt);
            }
        });

        Waktubox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jam", "Menit", "Detik" }));
        Waktubox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Waktubox1ActionPerformed(evt);
            }
        });
        Waktubox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Waktubox1KeyReleased(evt);
            }
        });

        Suhutxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SuhutxtKeyReleased(evt);
            }
        });

        Suhubox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "R", "F", "K" }));
        Suhubox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Suhubox1ItemStateChanged(evt);
            }
        });
        Suhubox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suhubox1ActionPerformed(evt);
            }
        });

        Jarakbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km", "hm", "dam", "m", "dm", "cm", "mm" }));
        Jarakbox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Jarakbox2ItemStateChanged(evt);
            }
        });
        Jarakbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jarakbox2ActionPerformed(evt);
            }
        });

        Waktubox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jam", "Menit", "Detik" }));
        Waktubox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Waktubox2ItemStateChanged(evt);
            }
        });
        Waktubox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Waktubox2ActionPerformed(evt);
            }
        });

        Suhubox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "R", "F", "K" }));
        Suhubox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Suhubox2ItemStateChanged(evt);
            }
        });
        Suhubox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suhubox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Suhutxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Waktutxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jaraktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jarakbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Waktubox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suhubox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Waktuhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Waktubox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Suhuhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Suhubox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jarakhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jarakbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jaraktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jarakbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jarakhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jarakbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Waktutxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Waktubox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Waktuhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Waktubox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Suhutxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suhubox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suhuhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suhubox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(17, 45, 78));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Converter");

        jButton1.setText("History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JaraktxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JaraktxtKeyReleased
       
    }//GEN-LAST:event_JaraktxtKeyReleased

    void jarakConverter() {
		double awal = 0;
		

		String jarakAsal = (String) Jarakbox1.getSelectedItem();
		String jarakAkhir = (String) Jarakbox2.getSelectedItem();

                try{
                    awal = Double.parseDouble(Jaraktxt.getText());
                    // Double.parseDouble(jarakAkhir);
                }catch(NumberFormatException e){
                    return;
                }
                
		Double hasil = Jarak.convert(jarakAsal, jarakAkhir) * awal;
		Jarakhasil.setText(String.valueOf(hasil));
	}
    private void WaktutxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WaktutxtKeyReleased
        waktuConvert();
    }//GEN-LAST:event_WaktutxtKeyReleased

    private void waktuConvert() {
		double awal = Double.parseDouble(Waktutxt.getText());

		String waktuAwal = (String) Waktubox1.getSelectedItem();
		String waktuAkhir = (String) Waktubox2.getSelectedItem();
                
//                if(!waktuAwal.matches("[0-9]+")){
//                    return;
//                }
//                
//                if(!waktuAkhir.matches("[0-9]+",".")){
//                    return;
//                }

		double hasil = Waktu.convert(waktuAwal, waktuAkhir) * awal;
		Waktuhasil.setText(String.valueOf(hasil));
	}
    private void SuhutxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SuhutxtKeyReleased
        tempratureConvert();
    }//GEN-LAST:event_SuhutxtKeyReleased

    private void tempratureConvert(){
        String suhuAsal = (String) Suhubox1.getSelectedItem();
        String suhuAkhir = (String) Suhubox2.getSelectedItem();

        double nilai = Double.parseDouble(Suhutxt.getText());

        double hasil = Suhu.coverter(suhuAsal, suhuAkhir, nilai);

        Suhuhasil.setText(String.valueOf(hasil));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Jarakbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jarakbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jarakbox1ActionPerformed

    private void Waktubox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Waktubox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Waktubox1ActionPerformed

    private void Suhubox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suhubox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Suhubox1ActionPerformed

    private void Jarakbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jarakbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jarakbox2ActionPerformed

    private void Waktubox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Waktubox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Waktubox2ActionPerformed

    private void Suhubox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suhubox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Suhubox2ActionPerformed

    private void Jarakbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Jarakbox1ItemStateChanged
        jarakConverter();
    }//GEN-LAST:event_Jarakbox1ItemStateChanged

    private void Waktubox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Waktubox1KeyReleased
        waktuConvert();
    }//GEN-LAST:event_Waktubox1KeyReleased

    private void Suhubox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Suhubox1ItemStateChanged
        tempratureConvert();
    }//GEN-LAST:event_Suhubox1ItemStateChanged

    private void Jarakbox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Jarakbox2ItemStateChanged
        jarakConverter();
    }//GEN-LAST:event_Jarakbox2ItemStateChanged

    private void Waktubox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Waktubox2ItemStateChanged
        waktuConvert();
    }//GEN-LAST:event_Waktubox2ItemStateChanged

    private void Suhubox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Suhubox2ItemStateChanged
        tempratureConvert();
    }//GEN-LAST:event_Suhubox2ItemStateChanged

    private void JaraktxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JaraktxtKeyPressed
        
    }//GEN-LAST:event_JaraktxtKeyPressed

    private void JaraktxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JaraktxtKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JaraktxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jarakbox1;
    private javax.swing.JComboBox<String> Jarakbox2;
    private javax.swing.JTextField Jarakhasil;
    private javax.swing.JTextField Jaraktxt;
    private javax.swing.JComboBox<String> Suhubox1;
    private javax.swing.JComboBox<String> Suhubox2;
    private javax.swing.JTextField Suhuhasil;
    private javax.swing.JTextField Suhutxt;
    private javax.swing.JComboBox<String> Waktubox1;
    private javax.swing.JComboBox<String> Waktubox2;
    private javax.swing.JTextField Waktuhasil;
    private javax.swing.JTextField Waktutxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
